sms/urls.py
from django.urls import path

from . import views
app_name ='sms'
urlpatterns = [
    path('index/', views.index, name='index'),

    path('message_User_insert/', views.message_User_insert, name='message_User_insert'),



    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register_submit/', views.register_submit, name='register_submit'),
    path('upload/', views.upload, name='upload'),
    path('createNotice/', views.createNotice, name='createNotice'),
    path('insert_notice/', views.insert_notice, name='insert_notice'),
    path('noticeDetail/<str:notice_pk>/', views.noticeDetail, name='noticeDetail'),
    path('m_noticeDetail/<str:notice_url>/', views.m_noticeDetail, name='m_noticeDetail'),


]

ysg/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ysg import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sms/',include('sms.urls', namespace='sms')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/models.py
from django.db import models

# Create your models here.

class Sender_User(models.Model):
    id = models.CharField(blank=False, null=False, primary_key=True, unique=True, max_length=200)
    ps = models.CharField(max_length=200, blank=False, null=False)
    aptNm = models.CharField(max_length=200, blank=True, null=True)
    complexNm= models.CharField(max_length=200, blank=True, null=True)
    villageNm =models.CharField(max_length=200, blank=True, null=True)
    aptAddress=models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        return str('%s' % (self.id))



class Notice(models.Model):
    notice_date = models.CharField(max_length=1200)
    notice_title =  models.CharField(max_length=200)
    notice_text = models.CharField(max_length=1200)
    notice_id= models.ForeignKey(Sender_User, on_delete=models.CASCADE)
    notice_pk=models.CharField(max_length=250 ,primary_key=True , unique=True)  # notice_date + notice_id


    def __str__(self):
        return str('%s' % (self.notice_pk))




class Message_User(models.Model):


    user_phoneNumber = models.CharField(max_length=200,)
    user_name =  models.CharField(max_length=200)
    user_dong = models.CharField(max_length=50, )
    user_hosu = models.CharField(max_length=50,)
    message_User_id=models.ForeignKey(Sender_User, on_delete=models.CASCADE)
    user_pk = models.CharField(max_length=250,primary_key=True , unique=True) # user_dong +  user_hosu



    def __str__(self):
        return str('%s ' % (self.user_pk))





class Message(models.Model):
    individual_notice_text = models.CharField(max_length=1200)
    notice_url = models.CharField(max_length=600,primary_key=True , unique=True)
    notice_pk  =models.ForeignKey(Notice, on_delete=models.CASCADE)
    isConfirmbyReceiver =models.BooleanField(default=False)
    user_pk =models.ForeignKey(Message_User, on_delete=models.CASCADE)
    notice_id=models.ForeignKey(Sender_User, on_delete=models.CASCADE)
    notice_Confirm_date =models.CharField(max_length=1200, blank=False, null=False)


    def __str__(self):
        return str('%s  ' % ( self.notice_url))



class Photo(models.Model):
    notice_pk = models.ForeignKey(Notice, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)




# https://docs.djangoproject.com/ko/3.1/intro/tutorial02/
# python manage.py makemigrations sms
#  python manage.py migrate
# python manage.py createsuperuser

sms/forms.py
from django import forms
from .models import  Message_User


class UploadFileForm(forms.Form):
    file=forms.FileField()

sms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

import sqlite3
import datetime

import openpyxl, pyexcel
from .models import Message, Message_User, Notice, Photo, Sender_User
import pandas as pd


from .func.katalk_send import katalk_send

from .forms import UploadFileForm

from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt




#-------------------함수 기반 view---------------------
# render 안쓴 것
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('sms/index_test.html')
#     context = {
#         'latest_question_list': latest_question_list,  # context를 통해 데이터를 전달
#     }
#     return HttpResponse(template.render(context, request))
# render 적용


@csrf_exempt
def index(request):
    if request.method == 'GET':
        conn = sqlite3.connect('./db.sqlite3')
        cur = conn.cursor()
        user_id = request.session.get('user')



        sql = "select * from sms_notice where notice_id_id =?"
        cur.execute(sql, [user_id])
        rows = cur.fetchall()
        rows = pd.DataFrame(rows)


        rows.rename(columns={0:"date", 1:"title",2:"text"},inplace=True)

        rate = []
        notice_pk=[]
        date =[] # 2021. 2. 16. 오전 11:28:54        2021-02-09 01:47:37

        if 0<len(rows):
            for i in rows['date']:
                receive_sum = 0
                date.append(i[:16])

                sql = "select isConfirmbyReceiver from sms_Message where notice_pk_id =?"

                notice_pk.append(i+" "+ user_id)
                cur.execute(sql, [i+" "+ user_id])
                print(i+" "+ user_id)
                row = cur.fetchall()
                print(row)
                for receive in row:

                    receive_sum+=receive[0]
                if receive_sum!=0:
                    rate.append(  round ( (receive_sum/len(row))* 100))
                else:
                    rate.append(0)
                # row = pd.DataFrame(row)




            title = rows['title']
            text = rows['text']



            request.session['user'] = user_id
            ## 공지 보낸 페이지 여기 까지


            ##=========== 유저 목록 데이터 ============

            sql = "select * from sms_Message_User where message_User_id_id =?"
            cur.execute(sql, [user_id])
            rows = cur.fetchall()
            rows = pd.DataFrame(rows)

            rows.rename(columns={0: "user_phoneNumber", 1: "user_name", 2: "user_dong",3:"user_hosu"}, inplace=True)



            user_phoneNumber = rows['user_phoneNumber']
            user_name = rows['user_name']
            user_dong = rows['user_dong']
            user_hosu = rows['user_hosu']

            sql = "select distinct user_dong from sms_Message_User where message_User_id_id =?"
            cur.execute(sql, [user_id])

            rows = cur.fetchall()
            dong_list = []
            group_list = {}


            for i in range(len(rows)):
                dong_list.append(rows[i][0])
                group_list[rows[i][0]]=[]



            sql = "select  user_dong, user_hosu from sms_Message_User where message_User_id_id =?"
            cur.execute(sql, [user_id])

            rows = cur.fetchall()



            for i in range(len(rows)):
                group_list[rows[i][0]].append(rows[i][1])


            history_data = zip(date, title, text,rate,notice_pk)

            user_data = zip(user_phoneNumber, user_name, user_dong,user_hosu,)




            return render(request, 'sms/index.html',{"history_data":history_data, "user_data":user_data,"dong_list":dong_list,"group_list":sorted(group_list.items()),"rate":rate})
        return render(request, 'sms/index.html')
    # conn = sqlite3.connect('./db.sqlite3')
    # cur = conn.cursor()
    # sql = "select distinct user_dong from  main.sms_message_user"
    #
    # cur.execute(sql)
    # rows = cur.fetchall()
    #
    # group_list=[]
    # for i in range(len(rows)):
    #     group_list.append(rows[i][0])
    #
    #
    #
    # return render(request, 'sms/index_test.html',{'kind': group_list})

@csrf_exempt
def insert_notice(request):
    if request.method == 'POST':

        user_id = request.session.get('user')
        request.session['user'] = user_id
        print(user_id)

        return render(request, 'sms/createNotice.html')


@csrf_exempt
def createNotice(request):

    if request.method == 'GET':
        conn = sqlite3.connect('./db.sqlite3')
        cur = conn.cursor()
        user_id = request.session.get('user')
        insert = request.GET.get('insert')



        sql = "select distinct user_dong from sms_Message_User where message_User_id_id =?"
        cur.execute(sql, [user_id])

        rows = cur.fetchall()
        dong_list = []
        group_list = {}
        insert_list = request.GET.getlist('input')
        dong = request.GET.get('group')

        if insert=="등록":



            insert_list.append(dong)
        elif 0!= len(insert_list):
            insert_list.pop(-1)




        for i in range(len(rows)):
            dong_list.append(rows[i][0])
            group_list[rows[i][0]] = []

        sql = "select  user_dong, user_hosu from sms_Message_User where message_User_id_id =?"
        cur.execute(sql, [user_id])

        rows = cur.fetchall()

        for i in range(len(rows)):
            group_list[rows[i][0]].append(rows[i][1])





        return render(request,'sms/createNotice.html',{"dong_list":dong_list,"group_list":sorted(group_list.items()), "insert_list":insert_list})
    if request.method == 'POST':
        # phone_number = request.POST.getlist('phone_number')
        # name = request.POST.getlist('name')

        conn = sqlite3.connect('./db.sqlite3')
        cur = conn.cursor()

        # 공지 DB Insert

        notice_text = request.POST.get('notice_text')
        notice_title = request.POST.get('notice_title')
        user_id = request.session.get('user')
        print(notice_text)

        now = datetime.datetime.now()
        nowDatetime = now.strftime('%Y-%m-%d %H:%M:%S')
        print(nowDatetime)


        # sql = "insert into sms_notice (notice_date,notice_title,notice_text,notice_id_id,notice_pk) values (?,?,?,?,?)"
        #
        # cur.execute(sql, [nowDatetime, str(notice_title), str(notice_text), str(user_id),nowDatetime +" "+str(user_id) ])
        #
        # conn.commit()

        notice = Notice()
        notice.notice_date = nowDatetime
        notice.notice_title = str(notice_title)
        notice.notice_text =str(notice_text)
        notice.notice_id_id = str(user_id)
        notice.notice_pk = nowDatetime +" "+str(user_id)
        notice.save()


        # 알림톡 수신자 data 가져오기
        group = request.POST.get('group')
        insert_list = request.POST.getlist('send')
        my_set = set(insert_list)  # 집합set으로 변환
        insert_list = list(my_set)  # list로 변환


        if "전체"  in insert_list :
            sql = "select * from  main.sms_message_user"
            cur.execute(sql)
        else:
            for i in range(len(insert_list)):

                sql = "select * from  main.sms_message_user where user_dong in (?) "

            cur.execute(sql, insert_list)

        rows = cur.fetchall()

        rows = pd.DataFrame(rows)

        print(rows)
        phone_number_list = rows[0]
        name = rows[1]
        user_dong_hosu_list=rows[4]

        for img in request.FILES.getlist('imgs'):

            #Photo 객체를 하나 생성한다.
            photo = Photo()
            # 외래키로 현재 생성한 Notice의 기본키를 참조한다.
            photo.notice_pk = notice
            # imgs로부터 가져온 이미지 파일 하나를 저장한다.
            photo.image = img
            # 데이터베이스에 저장
            photo.save()

        # sql = "insert into sms_photo (notice_date_id,image) values (?,?)"
        #
        # cur.execute(sql, [nowDatetime, str(img)])
        #
        # conn.commit()
        #
        # cur.close()
        # conn.close()

        # limit_time = request.POST.get('limit_time')
        send = katalk_send(name, phone_number_list,user_dong_hosu_list ,  str(notice_text), str(notice_title), str("12시"), str(user_id),
                           str(nowDatetime))
        send.send()

    return HttpResponseRedirect(
        reverse('sms:index', ))


@csrf_exempt
def noticeDetail(request,notice_pk):
    if request.method == "GET":
        user_id = request.session.get('user')


        conn = sqlite3.connect('./db.sqlite3')
        cur = conn.cursor()
        print(notice_pk)
        sql = "select * from sms_Notice where notice_pk = ?"
        notice = get_object_or_404(Notice, pk=notice_pk)
        cur.execute(sql,[str(notice_pk)])
        rows = cur.fetchall()

        title = rows[0][1]

        rows = pd.DataFrame(rows)

        rows.rename(columns={0: "date", 1: "title", 2: "text"}, inplace=True)
        day = rows['date']
        rate = []

        receive_sum = 0

        sql = "select isConfirmbyReceiver from sms_Message where notice_pk_id =?"


        cur.execute(sql, [notice_pk])

        row = cur.fetchall()

        ## 수신률 계산
        for receive in row:
            receive_sum += receive[0]
            print(receive[0])
        if receive_sum != 0:
            rate.append(round((receive_sum / len(row)) * 100))
        else:
            rate.append(0)
        # row = pd.DataFrame(row)


        ## 수신률 계산 끝


        ## 메세지  미확인자 확인자 체크
        sql = "select * from sms_Message where notice_pk_id = ?"
        cur.execute(sql,[str(notice_pk)])

        total = {}
        verify={}
        Nverify={}

        rows = cur.fetchall()

        for data in rows:
            sql = "select * from sms_Message_User where user_phoneNumber = ? and  message_User_id_id = ?"
            cur.execute(sql, [str(data[-1]), str(user_id)])

            dong_hosu=data[6].split(" ")

            total[dong_hosu[0]] = dong_hosu[1]  ## 동    호수 저장 딕셔너리

sms/templates/sms/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
<!--<h1>{{ question.question_text }}</h1>-->
<!--<ul>-->
<!--{% for choice in question.choice_set.all %}-->
<!--&lt;!&ndash;    question에 대해 외래키를 갇고있는 초이스를 모두 가져와라&ndash;&gt;-->
<!--&lt;!&ndash;<ol>태그는 ordered list의 약자로, 숫자나 알파벳 등 순서가 있는 목록을 만드는 데 사용합니다-->
<!--<ul>태그는 unordered list의 약자로, 순서가 필요 없는 목록을 만듭니다-->
<!--<dl>태그는 definition list의 약자로, 사전처럼 용어를 설명하는 목록을 만듭니다.-->
<!--<ol>과 <ul>의 각 항목들을 나열할 때는 <li> 태그를 사용하는데 list item의 약자입니다.&ndash;&gt;-->

<!--    <li>{{ choice.choice_text }}</li>-->
<!--{% endfor %} &lt;!&ndash; 말 그대로 endfor for 문 끝나는 지점 알려주기&ndash;&gt;-->



    <h1>{{ question.question_text }}</h1>
        part4
<a href="https://blog.outsider.ne.kr/312"> post와 get의 차이 </a> <br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<!--에러 메시지를 전달받으면 에러 메시지를 보여준다-->

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}  csfr토큰을 사용하여 CSRF 공격 기법을 우회할수있음 사이트간 위조 변조를 막기위함
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
<!--    input 태그는 사용자가 무언가를 입력할 수 있게 하는 태그-->
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>

{% endfor %}
<input type="submit" value="Vote">
</form>

</ul>
</body>
</html>

sms/templates/sms/login.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>로그인</title>

    <!-- Custom fonts for this template-->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}"  rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static "css/sb-admin-2.min.css" %}"  rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">로그인</h1>
                                    </div>


                                    <form class="user"action="{% url 'sms:login' %}" method="post" >

                                            {% csrf_token %}


                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="id" aria-describedby="emailHelp"  name="id" value="{{ id }}"
                                                placeholder="아이디">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"  name="ps" value="{{ ps }}"
                                                id="ps" placeholder="패스워드">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">ID 기억하기</label>
                                            </div>
                                        </div>
                                          <input type="submit" value="로그인" class="btn btn-primary btn-user btn-block">
<!--                                        <hr>-->
<!--                                        <a href="index.html" class="btn btn-google btn-user btn-block">-->
<!--                                            <i class="fab fa-google fa-fw"></i>구글로 로그인-->
<!--                                        </a>-->
<!--                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">-->
<!--                                            <i class="fab fa-facebook-f fa-fw"></i>페이스북으로 로그인-->
<!--                                        </a>-->
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">비밀번호 찾기</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="../register">회원가입</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}" ></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}" ></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}" ></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

sms/templates/sms/m_noticeDetail.html
<!DOCTYPE html>
<html lang="en">

<head>
{% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>아파트 공지 웹</title>

    <!-- Custom fonts for this template -->
   <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}"  rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
     <link href=	"{% static "css/sb-admin-2.min.css" %}"  rel="stylesheet">
</head>

<body id="page-top">

    <div class="card shadow">

		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary" style="font-size:200%"> >{{ title }}</h6>
		</div>
		<div class="card-body">
			<div class="text-center mb-4">

				{% for photo in notice.photo_set.all%}

					<img src="{{ photo.image.url }}" width="380"><br>
				{% endfor %}
<!--
<img  src= "{% static "img/porsche-911-carrera-4s-side-view.jpg" %}"   width="100%" height="200" urlclass="porsche"/>-->
			</div>
			<div class="mb-4">
				<p>{{ message_User.user_name }} 님 {{ message.individual_notice_text }} .<p>
			</div>
			<!-- Divider -->
			<hr class="sidebar-divider mb-4">
			<div class="text-right">
				<small class="form-text">발신자 : {{ sender_id}}</small>
				<small class="form-text">발신일 : {{ date }}</small>
			</div>
		</div>

	</div>
	<div class="card">
		<div class="card-header h6 font-weight-bold text-gray-800">
			지역 플레이스 출시 예정
		</div>
		<div class="card-body">
			<div class="card border-left-primary shadow h-100 py-2 mb-2">
				<div class="row">
<!--					<div class="col mt-4 mb-4">-->
<!--						<div class="text-xs font-weight-bold text-primary text-uppercase pl-4 mb-2">-->
<!--							포르쉐 세종점-->
<!--							<small>(거리 140m)</small>-->
<!--						</div>-->

<!--						<div class="h3 mb-0 bg-gradient-primary font-weight-bold text-gray-100 pt-2 pl-4 pb-2">-->
<!--							911 카레라 4S  40% 할인-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="col-auto mt-4" style="position:absolute; right:0">-->

<!--						<img  src= "{% static "img/porsche-911-carrera-4s-side-view.jpg" %}"   width="75px" height="75px" urlclass="porsche"/>-->
<!--					</div>-->
				</div>
			</div>
			
<!--			<div class="card border-left-success shadow h-100 py-2 mb-2">-->
<!--				<div class="row">-->
<!--					<div class="col mt-4 mb-4">-->
<!--						<div class="text-xs font-weight-bold text-success text-uppercase pl-4 mb-2">-->
<!--							페라리 조치원점-->
<!--							<small>(거리 520m)</small>-->
<!--						</div>-->
<!--						<div class="h6 mb-0 bg-gradient-success font-weight-bold text-gray-100 pt-2 pl-4 pb-2">-->
<!--							488 스피이더 60%할인-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="col-auto mt-4" style="position:absolute; right:0">-->
<!--						<img  src= "{% static "img/Ferrari.jpg" %}"   width="75px" height="75px" urlclass="porsche"/>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
			
<!--			<div class="card border-left-warning shadow h-100 py-2 mb-2">-->
<!--				<div class="row">-->
<!--					<div class="col mt-4 mb-4">-->
<!--						<div class="text-xs font-weight-bold text-warning text-uppercase pl-4 mb-2">-->
<!--							포르쉐 세종점-->
<!--							<small>(거리 140m)</small>-->
<!--						</div>-->
<!--						<div class="h3 mb-0 bg-gradient-warning font-weight-bold text-gray-100 pt-2 pl-4 pb-2">-->
<!--							911 케라라 4S 할인 60%-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="col-auto mt-4" style="position:absolute; right:0">-->
<!--						<img width="75px" height="75px" class="img-thumbnail bg-login-image"/>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
			
<!--			<div class="card border-left-danger shadow h-100 py-2 mb-2">-->
<!--				<div class="row">-->
<!--					<div class="col mt-4 mb-4">-->
<!--						<div class="text-xs font-weight-bold text-danger text-uppercase pl-4 mb-2">-->
<!--							맛나꽈배기-->
<!--							<small>(거리 20m)</small>-->
<!--						</div>-->
<!--						<div class="h6 mb-0 bg-gradient-danger font-weight-bold text-gray-100 pt-2 pl-4 pb-2">-->
<!--							꽈배기 1000원 4개-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="col-auto mt-4" style="position:absolute; right:0">-->
<!--						<img width="75px" height="75px" class="img-thumbnail bg-register-image"/>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
		</div>
	</div>

    <!-- Bootstrap core JavaScript-->
     <script src="{% static "vendor/jquery/jquery.min.js" %}" ></script>
       <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}" ></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}" ></script>

    <!-- Custom scripts for all pages-->
      <script src="{% static "js/sb-admin-2.min.js" %}" ></script>
</body>

</html>

sms/templates/sms/register.html
<!DOCTYPE html>
<html lang="en">

<head>



    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load static %}
    <title>관리자 계정 생성</title>

    <!-- Custom fonts for this template-->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->

    <link href= "{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">
	<link href= "{% static "css/custom.css" %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">관리자 계정 생성</h1>
                            </div>
                            <form class="user" action="{% url 'sms:register_submit' %}" method="post" >

                                 {% csrf_token %}


                                <div class="form-group row">
									<input type="email" class="form-control form-control-user" id="id"   name="id" value="{{ id }}"
										placeholder="ID를 입력해주세요 .(이메일)"  aria-describedby="emailHelp">
									<small class="form-text wd100 text-right"></small>
									
                                </div>
								<div class="form-group row">
									<input type="password" class="form-control form-control-user" id="ps" name="ps" value="{{ ps }}"
										placeholder="패스워드를 입력해주세요.">
									<small class="form-text wd100 text-right text-danger"></small>
                                </div>

								<div class="form-group row">
									<input type="text" class="form-control form-control-user" id="aptNm"  name="aptNm" value="{{ aptNm }}"
										placeholder="아파트명을 입력해주세요. ex 힐스테이트,자이">
                                </div>
								<div class="form-group row">
									<input type="text" class="form-control form-control-user" id="complexNm" name="complexNm" value="{{ complexNm }}"
										placeholder="단지명을 입력해주세요. ex 12단지, 6단지">
                                </div>
                                <div class="form-group row">
									<input type="text" class="form-control form-control-user" id="villageNm" name="villageNm" value="{{ villageNm }}"
										placeholder="마을명을 입력해주세요. ex 가재마을, 새뜸마을">
                                </div>

								<div class="form-group row">
									<input type="text" class="form-control form-control-user" id="aptAddress" name="aptAddress" value="{{ aptAddress }}"
										placeholder="아파트 주소를 입력해주세요. 필수값">
                                </div>
                                <input type="submit" value="가입" class="btn btn-primary btn-user btn-block">

                                </a>

                            </form>

                            <div class="text-center">
                                <a class="small" href="../login">로그인하러 가기</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Core plugin JavaScript-->

    <script src=  "{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <!-- Custom scripts for all pages-->
    <script src= "{% static "js/sb-admin-2.min.js" %}"></script>

</body>

</html>